all:
	@echo Need to give a target, nothing to do for all

run_sample:
	@node solution.js < input\sample.txt

run_01:
	@node solution.js < input\input01.txt

run_06:
	@node solution.js < input\input06.txt

run_07:
	@node solution.js < input\input07.txt

run_test:
	@node solution.js < input\test.txt
